### ISSUE TITLE
1.4.3.2 Modding API version

### ISSUE THREAD

**Issue by peekagrub** [hk-speedrunning/HK-Resources#1]
There are 2 versions of Modding API for 1.4.3.2, one made by Mulhima for 1432 and one ported from the 1.5.7.8 Modding API by pseudorandom. To my knowledge the port by pseudorandom is more up to date and also has the 1.5.7.8 versions of debug mod, benchwarp and srqol ported. 
So my question is which one do you want on here?

**Comment by ManicJamie** [comment]
My assumption is that the more modern api is the best to use for practice? In which case I'll add that and move the old API to legacy, as I assume the modern api is not compatible with old 1432 mods.

**Comment by ManicJamie** [comment]
To clarify: On searching #resources I am not seeing the 1432 backports, only backports for 1315 and 1028. The repos containing these also do not have releases, so I can't permalink direct downloads which is less than ideal but manageable.

**Comment by peekagrub** [comment]
We can ask pseudo if he wants to create releases, but yea old 1.4.3.2 mods aren't compatible to my knowledge.
