### ISSUE TITLE
New MiniSavestates builds for Linux and Mac

### ISSUE THREAD

**Issue by Yurihaia** [hk-speedrunning/HK-Resources#5]
Hey, I received this PR (https://github.com/Yurihaia/MiniSavestates/pull/1) adding Linux and Mac builds for MiniSavestates (1.5.xx only, but I will update the 1.2.2.1 and 1.0.2.8 builds as well) and just wanted to verify with a SRC mod that these builds are OK (although i doubt it will be a problem).

**Comment by Yurihaia** [comment]
As a side note, I think it might also be good to transfer the ownership of MiniSavestates to this github org so its not tied specifically to my account.

**Comment by ManicJamie** [comment]
Transferring ownership is probably the best solution if you don't wish to be sole point of contact, I have invited you to the org to get adequate permission per [the docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

**Comment by Yurihaia** [comment]
alright, will do.

**Comment by Yurihaia** [comment]
I will need repo managing perms for it to make sure the build script is working, but other than that it should be done.

**Comment by ManicJamie** [comment]
Have given Maintain perms in the repository, let me know if Admin is needed.
